#!/bin/bash

# Test if system can learn associations: output "world" when seeing "hello"
# This tests contextual learning, not just sequential patterns

set -e

BRAIN_FILE="test_association_brain.m"
INPUT_FILE="test_association_input.txt"

# Clean up from previous runs
rm -f "$BRAIN_FILE" "$INPUT_FILE"

echo "=== Testing Association Learning ==="
echo "Goal: System should learn to output 'world' when it sees 'hello'"
echo ""

# Step 1: Feed "hello world" multiple times to build the association
echo "=== Step 1: Training - Feed 'hello world' 5 times ==="
for i in 1 2 3 4 5; do
    echo "Training iteration $i: hello world"
    echo -n "hello world" > "$INPUT_FILE"
    ./melvin_standalone "$INPUT_FILE" "$BRAIN_FILE" 2>&1 | grep -E "(OUTPUT.*sampled_byte|Generation complete|Nodes:|Edges:)" | tail -3
    echo ""
done

echo "=== Step 2: Test - Feed 'hello' and see if it outputs 'world' ==="
echo -n "hello" > "$INPUT_FILE"
echo "Input: hello"
echo "Expected output: world (or at least starts with 'w')"
echo ""

# Capture full output
./melvin_standalone "$INPUT_FILE" "$BRAIN_FILE" 2>&1 | tee test_association_debug.log | grep -E "(OUTPUT.*sampled_byte|Generation complete|Node-based decision|Input-based decision)" | head -15

echo ""
echo "=== Analysis ==="

# Check what bytes were generated
if grep -q "OUTPUT.*sampled_byte" test_association_debug.log; then
    echo ""
    echo "Generated bytes:"
    grep "OUTPUT.*sampled_byte" test_association_debug.log | sed 's/.*sampled_byte=0x\([0-9a-f]*\).*/\1/' | while read hex; do
        printf "\\x$hex" | xxd -r -p | od -An -tx1 | tr -d ' \n' | sed 's/\(..\)/0x\1 /g'
    done
    echo ""
    
    # Check if 'w' (0x77) was generated
    if grep -q "sampled_byte=0x77" test_association_debug.log; then
        echo "✅ SUCCESS: System generated 'w' (first letter of 'world')!"
    else
        echo "⚠️  System did not generate 'w' - checking what it generated..."
        grep "sampled_byte=0x" test_association_debug.log | head -5
    fi
    
    OUTPUT_COUNT=$(grep -c "OUTPUT.*sampled_byte" test_association_debug.log || echo "0")
    echo "Total output bytes: $OUTPUT_COUNT"
else
    echo "⚠️  No output bytes generated"
fi

# Check graph statistics
echo ""
echo "=== Graph Statistics ==="
if [ -f "$BRAIN_FILE" ]; then
    FILE_SIZE=$(stat -f%z "$BRAIN_FILE" 2>/dev/null || stat -c%s "$BRAIN_FILE" 2>/dev/null || echo "0")
    echo "Brain file size: $FILE_SIZE bytes"
fi

# Check if 'hello' → 'world' association exists
echo ""
echo "=== Checking for 'hello' → 'world' association ==="
if grep -q "hello.*world\|world.*hello" test_association_debug.log; then
    echo "Found association in debug log"
else
    echo "Association not clearly visible in debug log"
fi


